### ISSUE TITLE
Crash whenever I try open apps tab (it's the installer app itself)

### ISSUE THREAD

**Issue by Sunniestar** [LemonLoader/MelonLoader#16]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

SystemUptimeMs: 48935955
Process: com.lavagang.melonloader.installer
PID: 22614
UID: 10679
Frozen: false
Flags: 0x30e8be44
Package: com.lavagang.melonloader.installer v1 (1.0.0)
Foreground: Yes
Process-Runtime: 2747
Timestamp: 2024-10-11 10:44:14.822-0500
Build: google/panther_beta/panther:15/AP41.240823.009/12329489:user/release-keys
Crash-Handler: mono.android.XamarinUncaughtExceptionHandler
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IndexOutOfBoundsException: offset(21) should be less than line limit(12)
	at android.text.TextLine.measure(TextLine.java:573)
	at android.text.Layout.getHorizontal(Layout.java:1690)
	at android.text.Layout.getHorizontal(Layout.java:1666)
	at android.text.Layout.getSecondaryHorizontal(Layout.java:1656)
	at android.text.Layout.getSecondaryHorizontal(Layout.java:1645)
	at crc6452ffdc5b34af3a0f.MauiTextView.n_onLayoutFormatted(Native Method)
	at crc6452ffdc5b34af3a0f.MauiTextView.onLayoutFormatted(MauiTextView.java:30)
	at com.microsoft.maui.PlatformAppCompatTextView.onLayout(PlatformAppCompatTextView.java:31)
	at android.view.View.layout(View.java:25404)
	at crc6452ffdc5b34af3a0f.LayoutViewGroup.n_onLayout(Native Method)
	at crc6452ffdc5b34af3a0f.LayoutViewGroup.onLayout(LayoutViewGroup.java:67)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(Native Method)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(ContentViewGroup.java:67)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(Native Method)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(ContentViewGroup.java:67)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at crc64e1fb321c08285b90.ViewCellRenderer_ViewCellContainer.n_onLayout(Native Method)
	at crc64e1fb321c08285b90.ViewCellRenderer_ViewCellContainer.onLayout(ViewCellRenderer_ViewCellContainer.java:85)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.ListView.setupChild(ListView.java:2175)
	at android.widget.ListView.makeAndAddView(ListView.java:2068)
	at android.widget.ListView.fillDown(ListView.java:791)
	at android.widget.ListView.fillFromTop(ListView.java:853)
	at android.widget.ListView.layoutChildren(ListView.java:1836)
	at android.widget.AbsListView.onLayout(AbsListView.java:2271)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at crc64e1fb321c08285b90.ListViewRenderer.n_onLayout(Native Method)
	at crc64e1fb321c08285b90.ListViewRenderer.onLayout(ListViewRenderer.java:75)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(Native Method)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(ContentViewGroup.java:67)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at crc640ec207abc449b2ca.ShellPageContainer.n_onLayout(Native Method)
	at crc640ec207abc449b2ca.ShellPageContainer.onLayout(ShellPageContainer.java:58)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10321)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1720)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4307)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2376)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1273)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1880)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1640)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:762)
	at android.view.View.layout(View.java:25404)
	at android.view.ViewGroup.layout(ViewGroup.java:6435)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4109)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2973)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10414)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1424)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1024)
	at android.view.Choreographer.doFrame(Choreographer.java:953)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1398)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8756)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
^This is the crash log from the installer app itself from adb shell dumpsys (shizuku) using android 15 beta at the moment

### Did you attach your log file?

No, I could not find a log file

**Comment by Sunniestar** [comment]
One more thing it works when I install it private space so I'm assuming it has to do with how many apps I have installed
![Screenshot_20241011-110028](https://github.com/user-attachments/assets/74ba834b-7b8a-4d4d-8ead-b3736ec6701e)

**Comment by Sunniestar** [comment]
Compared to my private spaces apps installed
![1000001045](https://github.com/user-attachments/assets/cacd62d7-e6b3-4670-bc30-0b97b4b4ec99)
