### ISSUE TITLE
[Bug]: Not working with batman shadow

### ISSUE THREAD

**Issue by xAstroBoy** [LemonLoader/MelonLoader#27]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the app.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting the device.

### Describe the issue.

i forced the installation after i found the engine version which is 2022.3.41

yet the modloader won't launch

The log says everything, i am trying to make a mod for batman shadow and i see is failing.

[19:41:30.406] Initialized JNI
[19:41:30.712] ------------------------------
[19:41:30.714] MelonLoader v0.6.5 Open-Beta
[19:41:30.718] OS: Android 12L
[19:41:30.718] Hash Code: 5CD70450DB040884645CC87694335EB2DEFBB8CE840FC149EED709EAD3D2B03F
[19:41:30.718] ------------------------------
[19:41:30.718] Game Type: Il2cpp
[19:41:30.718] Game Arch: x64
[19:41:30.719] ------------------------------
[19:41:30.720] Command-Line: 
[19:41:30.721] ------------------------------
[19:41:30.721] Core::BasePath = /storage/emulated/0/MelonLoader/com.camouflaj.manta
[19:41:30.722] Game::BasePath = /storage/emulated/0/MelonLoader/com.camouflaj.manta
[19:41:30.722] Game::DataPath = bin/Data/
[19:41:30.723] Game::ApplicationPath = /system/bin/app_process64
[19:41:30.723] Runtime Type: net8
[19:41:30.983] ------------------------------
[19:41:30.983] Game Name: UNKNOWN
[19:41:30.983] Game Developer: UNKNOWN
[19:41:30.993] Unity Version: 0.0.0a0
[19:41:30.993] Game Version: UNKNOWN
[19:41:30.993] ------------------------------

[19:41:32.185] DotnetAssemblyLoadContextFix Exception: System.NullReferenceException: Null method for MelonLoader
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer, HarmonyMethod ilmanipulator)
   at MelonLoader.Fixes.DotnetAssemblyLoadContextFix.Install()
[19:41:32.652] HarmonyLib.HarmonyException: IL Compile Error (unknown location)
 ---> HarmonyLib.HarmonyException: IL Compile Error (unknown location)
 ---> System.MissingMethodException: Method not found: void Il2CppInterop.Runtime.Injection.RegisterTypeOptions.set_LogSuccess(bool)
   at System.RuntimeMethodHandle.GetFunctionPointer()
   at MonoMod.Core.Platforms.Runtimes.MonoRuntime.Compile(MethodBase method)
   at MonoMod.Core.Platforms.PlatformTriple.Compile(MethodBase method)
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.UpdateEndOfChain()
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.AddILHook(SingleILHookState ilhook, Boolean takeLock)
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement)
   --- End of inner exception stack trace ---
   at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer, HarmonyMethod ilmanipulator)
   at MelonLoader.Fixes.Il2CppInteropFixes.Install()
[19:41:32.878] Preferences Loaded!

[19:41:32.994] Loading UserLibs from '/storage/emulated/0/MelonLoader/com.camouflaj.manta/UserLibs'...

[19:41:33.001] Loading Plugins from '/storage/emulated/0/MelonLoader/com.camouflaj.manta/Plugins'...
[19:41:33.008] 0 Plugins loaded.

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
It seems like the game uses a modified Unity version which confuses basically every part of the loader. I don't have any plans on implementing support for modified Unity versions.
