### ISSUE TITLE
[Bug]: Crash due to MissingMethodException with Il2CppInterop method.

### ISSUE THREAD

**Issue by developerman9876** [LemonLoader/MelonLoader#33]
### All of the following criteria must be met

- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the app.
- [ ] Tried reinstalling LemonLoader.
- [ ] Tried restarting the device.

### Describe the issue.

[14:49:48.172] Initialized JNI
[14:49:48.468] ------------------------------
[14:49:48.470] MelonLoader v0.6.5 Open-Beta
[14:49:48.474] OS: Android 12L
[14:49:48.474] Hash Code: 5CD70450DB040884645CC87694335EB2DEFBB8CE840FC149EED709EAD3D2B03F
[14:49:48.475] ------------------------------
[14:49:48.475] Game Type: Il2cpp
[14:49:48.475] Game Arch: x64
[14:49:48.475] ------------------------------
[14:49:48.477] Command-Line: 
[14:49:48.477] ------------------------------
[14:49:48.478] Core::BasePath = /storage/emulated/0/MelonLoader/com.LuWiGames.MonkeysPlaceV2
[14:49:48.478] Game::BasePath = /storage/emulated/0/MelonLoader/com.LuWiGames.MonkeysPlaceV2
[14:49:48.478] Game::DataPath = bin/Data/
[14:49:48.479] Game::ApplicationPath = /system/bin/app_process64
[14:49:48.480] Runtime Type: net8
[14:49:48.929] ------------------------------
[14:49:48.929] Game Name: MonkeysRealm
[14:49:48.930] Game Developer: LuWiGames
[14:49:48.939] Unity Version: 2020.3.48f1
[14:49:48.940] Game Version: 2.3
[14:49:48.940] ------------------------------

[14:49:50.547] DotnetAssemblyLoadContextFix Exception: System.NullReferenceException: Null method for MelonLoader
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer, HarmonyMethod ilmanipulator)
   at MelonLoader.Fixes.DotnetAssemblyLoadContextFix.Install()
[14:49:51.193] HarmonyLib.HarmonyException: IL Compile Error (unknown location)
 ---> HarmonyLib.HarmonyException: IL Compile Error (unknown location)
 ---> System.MissingMethodException: Method not found: void Il2CppInterop.Runtime.Injection.RegisterTypeOptions.set_LogSuccess(bool)
   at System.RuntimeMethodHandle.GetFunctionPointer()
   at MonoMod.Core.Platforms.Runtimes.MonoRuntime.Compile(MethodBase method)
   at MonoMod.Core.Platforms.PlatformTriple.Compile(MethodBase method)
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.UpdateEndOfChain()
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.AddILHook(SingleILHookState ilhook, Boolean takeLock)
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement)
   --- End of inner exception stack trace ---
   at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer, HarmonyMethod ilmanipulator)
   at MelonLoader.Fixes.Il2CppInteropFixes.Install()
[14:49:51.519] Preferences Loaded!

[14:49:51.631] Loading UserLibs from '/storage/emulated/0/MelonLoader/com.LuWiGames.MonkeysPlaceV2/UserLibs'...

[14:49:51.642] Loading Plugins from '/storage/emulated/0/MelonLoader/com.LuWiGames.MonkeysPlaceV2/Plugins'...
[14:49:51.652] 0 Plugins loaded.
[14:49:52.600] Loading Il2CppAssemblyGenerator...
[14:49:52.699] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[14:49:54.052] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/monkeysrealm)
[14:49:54.052] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[14:49:54.052] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[14:49:54.052] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[14:49:54.053] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[14:49:54.077] [Il2CppAssemblyGenerator] Using Cpp2IL Version: 2022.1.0-pre-release.16
[14:49:54.077] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6+5c0c44bfc31bc50023fb7426fc4a32b2086f672b
[14:49:54.077] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2020.3.48
[14:49:54.078] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[14:49:54.079] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[14:49:54.079] [Il2CppAssemblyGenerator] Checking GameAssembly...
[14:49:54.340] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[14:49:54.342] Loading Mods from '/storage/emulated/0/MelonLoader/com.LuWiGames.MonkeysPlaceV2/Mods'...
[14:49:54.344] 0 Mods loaded.

[14:49:55.059] [Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[14:49:55.185] [Il2CppInterop] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[14:49:55.199] [Il2CppInterop] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[14:49:55.249] Support Module Loaded: /storage/emulated/0/MelonLoader/com.LuWiGames.MonkeysPlaceV2/MelonLoader/Dependencies/SupportModules/Il2Cpp.dll
[14:50:14.817] Preferences Saved!
[14:50:14.977] [Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: HarmonyLib.HarmonyException: IL Compile Error (unknown location)
 ---> HarmonyLib.HarmonyException: IL Compile Error (unknown location)
 ---> System.MissingMethodException: Method not found: void Il2CppInterop.Runtime.Injection.RegisterTypeOptions.set_LogSuccess(bool)
   at System.RuntimeMethodHandle.GetFunctionPointer()
   at MonoMod.Core.Platforms.Runtimes.MonoRuntime.Compile(MethodBase method)
   at MonoMod.Core.Platforms.PlatformTriple.Compile(MethodBase method)
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.UpdateEndOfChain()
   at MonoMod.RuntimeDetour.DetourManager.ManagedDetourState.AddILHook(SingleILHookState ilhook, Boolean takeLock)
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement)
   --- End of inner exception stack trace ---
   at HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo(MethodBase replacement)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at DMD<Unpatch>?1655573844._HarmonyLib_PatchProcessor::Unpatch(PatchProcessor this, MethodInfo patch)
   at DMD<>?1655573844.SyncProxy<HarmonyLib.PatchProcessor HarmonyLib.PatchProcessor:Unpatch(System.Reflection.MethodInfo)>(PatchProcessor , MethodInfo )
   at HarmonyLib.PatchFunctions.<>c__DisplayClass5_0.<UnpatchConditional>b__3(Patch patchInfo)
   at HarmonyLib.CollectionExtensions.Do[Patch](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.CollectionExtensions.DoIf[Patch](IEnumerable`1 sequence, Func`2 condition, Action`1 action)
   at HarmonyLib.PatchFunctions.UnpatchConditional(Func`2 executionCondition)
   at HarmonyLib.Harmony.UnpatchID(String harmonyID)
   at HarmonyLib.Harmony.UnpatchSelf()
   at MelonLoader.Core.Quit()
   at MelonLoader.SupportModule_From.DefiniteQuit()
   at MelonLoader.Support.SM_Component.OnApplicationDefiniteQuit()
   at MelonLoader.Support.SM_Component.OnDestroy()
   at MelonLoader.Support.SM_Component.Trampoline_VoidThisMelonLoader.Support.SM_ComponentOnDestroy(IntPtr , Il2CppMethodInfo* )

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by TrevTV** [comment]
I don't support GTAG or clones.

**Comment by developerman9876** [comment]
It isn't GTAG nor a clone...
